apiVersion: v1  
kind: Pod
metadata: 
  name: test-pod
spec:   
  containers:   
    - name: test-ts 
      image: redis  
      command: [ "/bin/sh", "-c", "env" ]   
      env:   
        # Define the environment variable   
        - name: SPECIAL_NAME  
          valueFrom:   
            configMapKeyRef:  
              name: first-test   
              key: emri
        - name: SPECIAL_NR  
          valueFrom:   
            configMapKeyRef:  
              name: first-test   
              key: test 
  restartPolicy: Never