apiVersion: v1 
kind: Pod  
metadata:  
  name: test-pod  
spec:  
  containers:  
    - name: test  
      image: redis  
      command: [ "/bin/sh", "-c", "env" ]  
      envFrom:  
      - configMapRef:  
          name: special-config  
  restartPolicy: Never
  