apiVersion: v1  
kind: Pod
metadata: 
  name: test-pod
spec:   
  containers:   
    - name: test 
      image: redis  
      command: [ "/bin/sh", "-c", "env" ]   
      env:   
        # Define the environment variable   
        - name: SPECIAL_LEVEL_KEY   
          valueFrom:   
            configMapKeyRef:  
              name: first-config    
              key: low.config  
  restartPolicy: Never