apiVersion: v1  
kind: Pod  
metadata:  
  name: test-pod  
spec:  
  containers:  
    - name: test 
      image: redis  
      command: [ "/bin/sh", "-c", "env" ]  
      env:  
        - name: SPECIAL_LEVEL_KEY  
          valueFrom:  
            configMapKeyRef:  
              name: special-config  
              key: special.how  
        - name: LOG_LEVEL  
          valueFrom:  
            configMapKeyRef:  
              name: env-config  
              key: log_level  
  restartPolicy: Never
  